#!/bin/sh
#

# CMD
# CONT:Used to start/stop Apache2
# OPT:kite apache [start | stop | restart | status]

if [ a$1 = a -o a$1 = astatus ];
then
	echo
	sudo service apache2 status | grep Active
fi

if [ a$1 = astart ];
then
	sudo service apache2 start > /dev/null
	echo
	sudo service apache2 status | grep Active
fi

if [ a$1 = astop ];
then
	sudo service apache2 stop > /dev/null
	echo
	sudo service apache2 status | grep Active
fi

if [ a$1 = arestart ];
then
	sudo service apache2 restart > /dev/null
	echo
	sudo service apache2 status | grep Active
fi
